In [3]:
# 2.1 리스트로 배열 생성
# 4-1. 1차원 배열(list)로 numpy 배열 생성
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# 4-2. 2차원 배열(list)로 numpy 배열 생성
arr = np.array([[1,2,3],[4,5,6]]) # 두 튜플을 한 번 더 []로 감싸줘야 함
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 4-3. 3차원 배열(list)로 numpy 배열 생성
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# 2.2 