In [3]:
# 2.1 리스트로 배열 생성
# 4-1. 1차원 배열(list)로 numpy 배열 생성
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# 4-2. 2차원 배열(list)로 numpy 배열 생성
arr = np.array([[1,2,3],[4,5,6]]) # 두 튜플을 한 번 더 []로 감싸줘야 함
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 4-3. 3차원 배열(list)로 numpy 배열 생성
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
# 2.2 배열 생성 및 초기화
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a = np.full((3,3),1.5)
print(a)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [13]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.arrange() 함수 </br>
numpy.arrange([start,],stop[,step,], dtype=None) </br>
- start부터 stop 미만까지 step 간격으로 데이터 생성한 후 배열을 생성
- 범위 내에서 간격을 기준 균등 간격의 배열
- 요소의 개수가 아닌 데이터의 간격을 기준으로 배열 생성


In [15]:
# 2.3 생성한 값으로 배열 생성
# 4-4 
# arrange() : 정수 범위로 배열 생성
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### np.linspace()
- numpy.linspace(start,stop,num=50, endpoint=True, retstep=False, dtype = None) </br>
- start부터 stop 범위에서 num개를 균일한 간격으로 데이터를 생성하고 배열을 만드는 함수
- 요소 개수를 기준으로 균등 간격의 배열 생성

In [16]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


### np.logspace() 
numpy.logspace(start,stop, num=50, endpoint=True, base=10.0, dtype=None) </br>
- 로그 스케일의 linspace 함수
- 로그 스케일로 지정된 범위에서 num 개수만큼 균등간격으로 데이터 생성한 후 배열 생성


In [17]:
# 4-6 
a = np.logspace(np.log10(10),np.log10(100),5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [18]:
a = np.logspace(1,2,5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]
