tech blog : https://doleebest.tistory.com/55

# 2.1 리스트로 배열 생성

In [3]:
# 4-1. 1차원 배열(list)로 numpy 배열 생성
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# 4-2. 2차원 배열(list)로 numpy 배열 생성
arr = np.array([[1,2,3],[4,5,6]]) # 두 튜플을 한 번 더 []로 감싸줘야 함
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 4-3. 3차원 배열(list)로 numpy 배열 생성
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


# 2.2 배열 생성 및 초기화

In [8]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a = np.full((3,3),1.5)
print(a)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [13]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.arrange() 함수 </br>
numpy.arrange([start,],stop[,step,], dtype=None) </br>
- start부터 stop 미만까지 step 간격으로 데이터 생성한 후 배열을 생성
- 범위 내에서 간격을 기준 균등 간격의 배열
- 요소의 개수가 아닌 데이터의 간격을 기준으로 배열 생성


In [15]:
# 2.3 생성한 값으로 배열 생성
# 4-4 
# arrange() : 정수 범위로 배열 생성
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### np.linspace()
- numpy.linspace(start,stop,num=50, endpoint=True, retstep=False, dtype = None) </br>
- start부터 stop 범위에서 num개를 균일한 간격으로 데이터를 생성하고 배열을 만드는 함수
- 요소 개수를 기준으로 균등 간격의 배열 생성

In [16]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


### np.logspace() 
numpy.logspace(start,stop, num=50, endpoint=True, base=10.0, dtype=None) </br>
- 로그 스케일의 linspace 함수
- 로그 스케일로 지정된 범위에서 num 개수만큼 균등간격으로 데이터 생성한 후 배열 생성


In [17]:
# 4-6 
a = np.logspace(np.log10(10),np.log10(100),5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [18]:
a = np.logspace(1,2,5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


# 2.4 난수 기반으로 배열 생성
numpy.random

In [20]:
a=np.random.random()
print(a)

0.9535235053742798


In [22]:
a=np.random.random((4,4))
print(a)

[[0.59196888 0.68468625 0.2442402  0.6815715 ]
 [0.92795167 0.48239375 0.23077028 0.41880925]
 [0.44626693 0.29571064 0.24565092 0.10317056]
 [0.90879664 0.39993027 0.36119185 0.76402791]]


### randint()
numpy.random.randint(low,high=None, size=None, dtype='l')</br>
지정된 shape로 배열을 만들고 low부터 high 미만의 범위에서 정수 표본 추출

In [24]:
a=np.random.randint(1,10) # 1차원 배열 만들고, 1부터 10 미만의 범위에서 정수 표본 추출
print(a)

9


In [25]:
a = np.random.randint(1,10,(4,4))
print(a)

[[4 1 8 8]
 [1 3 7 7]
 [7 5 3 2]
 [5 9 6 9]]


### rand() 함수
numpy.random.rand(d0,d1, ..., dn) </br>
- shape이 (d0,d1, ..., dn)인 배열 생성 후 난수로 초기화
- 난수 : [0,1)의 균등 분포 (uniform distribution) 형상으로 표본 추출

In [26]:
# rand() : 균등분포를 고려한 랜덤한 수의 배열 생성
a = np.random.rand(3,3)
print(a)

[[0.51242059 0.14167609 0.13670487]
 [0.10776096 0.78895233 0.86982765]
 [0.06559343 0.63115054 0.48265979]]


### randn() 함수
numpy.random.randn(d0,d1, ... ,dn)
- (d0,d1, ... ,dn) shape 배열 생성 후 난수로 초기화
- 난수 : 표준 정규 분포(standard normal distribution) 에서 표본 추출


In [27]:
a = np.random.randn(3,3)
print(a)

[[-0.45620621 -0.51407998  0.55664163]
 [-0.14189553 -1.25671518  0.37853542]
 [-0.25543915  0.42045563 -0.35586019]]


# 3. 넘파이 배열 조회
### 3.1 넘파이 표준 데이터 타입

### 3.2 넘파일 배열 속성 정보

In [28]:
arr = np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [31]:
print('ndim :' ,arr.ndim)

ndim : 1


In [32]:
print('shape :',arr.shape)

shape : (5,)


In [33]:
print('dtype : ', arr.dtype)

dtype :  int64


In [34]:
print('size :', arr.size)

size : 5


In [35]:
print('itemsize : ', arr.itemsize) # 정수는 8바이트

itemsize :  8


In [36]:
print('nbytes : ', arr.nbytes)

nbytes :  40


## 3.3 배열의 인덱싱

In [37]:
# 4-12 : 1차원 배열의 인덱싱 및 변경
a1 = np.arange(9) # 1차원 배열
print(a1)
print(a1[0])
print(a1[-1])
a1[0]=10 # 요소 변경
print(a1)

[0 1 2 3 4 5 6 7 8]
0
8
[10  1  2  3  4  5  6  7  8]


In [38]:
a2 = np.arange(9).reshape((3,3)) # 2차원 배열
print(a2)
print(a2[0,1]) # 1행 두번째 컬럼 요소 참조
print(a2[1,2]) # 2행 세번째 컬럼 요소 참조
a2[0,0] = 10 # 1행 첫번째 컬럼 업데이트
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
5
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [40]:
# 4-14 : 일차원 배열의 슬라이싱
a1 = np.arange(6)
print(a1)
print(a1[0:3])
print(a1[1:])
print(a1[-2:])
print(a1[:-3])
print(a1[::2]) # with a step size of 2
print(a1[::-1])

[0 1 2 3 4 5]
[0 1 2]
[1 2 3 4 5]
[4 5]
[0 1 2]
[0 2 4]
[5 4 3 2 1 0]


In [41]:
# 4-15 : 2치원 배열의 슬라이싱
a2 = np.arange(1,25).reshape((4,6))
print(a2[1])
print(a2[1:3,1:5])
print(a2[2,:])
print(a2[:3,:3])
print(a2[2:,::-1])
print(a2[::-1,::-1])

[ 7  8  9 10 11 12]
[[ 8  9 10 11]
 [14 15 16 17]]
[13 14 15 16 17 18]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]
