tech blog : https://doleebest.tistory.com/55

# 2.1 리스트로 배열 생성

In [3]:
# 4-1. 1차원 배열(list)로 numpy 배열 생성
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# 4-2. 2차원 배열(list)로 numpy 배열 생성
arr = np.array([[1,2,3],[4,5,6]]) # 두 튜플을 한 번 더 []로 감싸줘야 함
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# 4-3. 3차원 배열(list)로 numpy 배열 생성
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]],
               [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


# 2.2 배열 생성 및 초기화

In [8]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a = np.full((3,3),1.5)
print(a)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [13]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### np.arrange() 함수 </br>
numpy.arrange([start,],stop[,step,], dtype=None) </br>
- start부터 stop 미만까지 step 간격으로 데이터 생성한 후 배열을 생성
- 범위 내에서 간격을 기준 균등 간격의 배열
- 요소의 개수가 아닌 데이터의 간격을 기준으로 배열 생성


In [15]:
# 2.3 생성한 값으로 배열 생성
# 4-4 
# arrange() : 정수 범위로 배열 생성
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### np.linspace()
- numpy.linspace(start,stop,num=50, endpoint=True, retstep=False, dtype = None) </br>
- start부터 stop 범위에서 num개를 균일한 간격으로 데이터를 생성하고 배열을 만드는 함수
- 요소 개수를 기준으로 균등 간격의 배열 생성

In [16]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


### np.logspace() 
numpy.logspace(start,stop, num=50, endpoint=True, base=10.0, dtype=None) </br>
- 로그 스케일의 linspace 함수
- 로그 스케일로 지정된 범위에서 num 개수만큼 균등간격으로 데이터 생성한 후 배열 생성


In [17]:
# 4-6 
a = np.logspace(np.log10(10),np.log10(100),5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


In [18]:
a = np.logspace(1,2,5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


# 2.4 난수 기반으로 배열 생성
numpy.random

In [20]:
a=np.random.random()
print(a)

0.9535235053742798


In [22]:
a=np.random.random((4,4))
print(a)

[[0.59196888 0.68468625 0.2442402  0.6815715 ]
 [0.92795167 0.48239375 0.23077028 0.41880925]
 [0.44626693 0.29571064 0.24565092 0.10317056]
 [0.90879664 0.39993027 0.36119185 0.76402791]]


### randint()
numpy.random.randint(low,high=None, size=None, dtype='l')</br>
지정된 shape로 배열을 만들고 low부터 high 미만의 범위에서 정수 표본 추출

In [24]:
a=np.random.randint(1,10) # 1차원 배열 만들고, 1부터 10 미만의 범위에서 정수 표본 추출
print(a)

9


In [25]:
a = np.random.randint(1,10,(4,4))
print(a)

[[4 1 8 8]
 [1 3 7 7]
 [7 5 3 2]
 [5 9 6 9]]


### rand() 함수
numpy.random.rand(d0,d1, ..., dn) </br>
- shape이 (d0,d1, ..., dn)인 배열 생성 후 난수로 초기화
- 난수 : [0,1)의 균등 분포 (uniform distribution) 형상으로 표본 추출

In [26]:
# rand() : 균등분포를 고려한 랜덤한 수의 배열 생성
a = np.random.rand(3,3)
print(a)

[[0.51242059 0.14167609 0.13670487]
 [0.10776096 0.78895233 0.86982765]
 [0.06559343 0.63115054 0.48265979]]


### randn() 함수
numpy.random.randn(d0,d1, ... ,dn)
- (d0,d1, ... ,dn) shape 배열 생성 후 난수로 초기화
- 난수 : 표준 정규 분포(standard normal distribution) 에서 표본 추출


In [27]:
a = np.random.randn(3,3)
print(a)

[[-0.45620621 -0.51407998  0.55664163]
 [-0.14189553 -1.25671518  0.37853542]
 [-0.25543915  0.42045563 -0.35586019]]


# 3. 넘파이 배열 조회
### 3.1 넘파이 표준 데이터 타입

### 3.2 넘파일 배열 속성 정보

In [28]:
arr = np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [31]:
print('ndim :' ,arr.ndim)

ndim : 1


In [32]:
print('shape :',arr.shape)

shape : (5,)


In [33]:
print('dtype : ', arr.dtype)

dtype :  int64


In [34]:
print('size :', arr.size)

size : 5


In [35]:
print('itemsize : ', arr.itemsize) # 정수는 8바이트

itemsize :  8


In [36]:
print('nbytes : ', arr.nbytes)

nbytes :  40


## 3.3 배열의 인덱싱

In [37]:
# 4-12 : 1차원 배열의 인덱싱 및 변경
a1 = np.arange(9) # 1차원 배열
print(a1)
print(a1[0])
print(a1[-1])
a1[0]=10 # 요소 변경
print(a1)

[0 1 2 3 4 5 6 7 8]
0
8
[10  1  2  3  4  5  6  7  8]


In [38]:
a2 = np.arange(9).reshape((3,3)) # 2차원 배열
print(a2)
print(a2[0,1]) # 1행 두번째 컬럼 요소 참조
print(a2[1,2]) # 2행 세번째 컬럼 요소 참조
a2[0,0] = 10 # 1행 첫번째 컬럼 업데이트
print(a2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
5
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [40]:
# 4-14 : 일차원 배열의 슬라이싱
a1 = np.arange(6)
print(a1)
print(a1[0:3])
print(a1[1:])
print(a1[-2:])
print(a1[:-3])
print(a1[::2]) # with a step size of 2
print(a1[::-1])

[0 1 2 3 4 5]
[0 1 2]
[1 2 3 4 5]
[4 5]
[0 1 2]
[0 2 4]
[5 4 3 2 1 0]


In [41]:
# 4-15 : 2치원 배열의 슬라이싱
a2 = np.arange(1,25).reshape((4,6))
print(a2[1])
print(a2[1:3,1:5])
print(a2[2,:])
print(a2[:3,:3])
print(a2[2:,::-1])
print(a2[::-1,::-1])

[ 7  8  9 10 11 12]
[[ 8  9 10 11]
 [14 15 16 17]]
[13 14 15 16 17 18]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]
[[24 23 22 21 20 19]
 [18 17 16 15 14 13]
 [12 11 10  9  8  7]
 [ 6  5  4  3  2  1]]


### 3.5 Logical indexing 

In [42]:
# 4-16 boolean indexing : 배열 각 요소의 선택 여부 불린을 지정하는 방식, 해당 인덱스의 true만 조회한다.
a = np.arange(1,6)
print(a)
b = [True, False, False, True, False]
print(a[b])

[1 2 3 4 5]
[1 4]


In [44]:
# 불린 인덱싱 : 비교 연산자 이용
a = np.arange(11)
print(a[a<5])
five_up = (a>=5)
five_up
print(a[five_up])
divide_by_2 = a[a%2==0]
print(divide_by_2)

[0 1 2 3 4]
[ 5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [45]:
# 4-18 : 관계 연산자 이용

# 논리 연산자 이용 (&, |, ~)
c = a[(a>5) & (a<11)] # and
print(c)
d = a[(a>9 | (a<5))] # or
print(d)
e = a[~(a%3==0)] # not
print(e)

[ 6  7  8  9 10]
[10]
[ 1  2  4  5  7  8 10]


# 4) 배열의 연산

In [46]:
# 4-19 : 산술 연산 : 사칙연산 연산자와 함수 활용
a = np.arange(1,11)
b = np.arange(1,11)
print(a+b)
print(np.add(a,b)) # 덧셈 함수
print(a-b)
print(np.subtract(a,b)) # 뺄셈 함수
print(a*b)
print(np.multiply(a,b))
print(a/b)
print(np.divide(a,b)) # 나눗셈 함수

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]
[  1   4   9  16  25  36  49  64  81 100]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [47]:
# 4-20 기타 연산 : 지수/제곱근/sin/cos/tan/log
a = np.arange(1,11)
print(np.exp(a)) 
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log(a))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566  0.64836083]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 집계 함수

In [50]:
# 4-21 [ndarray 배열 객체].sum(), np.sum()
a = np.arange(1,10).reshape(3,3)
print(a.sum())
print(np.sum(a)) # 둘이 같은 표현

print(a)

b = a.sum(axis=0)
print(b)

c = a.sum(axis=1)
print(c)

45
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [52]:
# 4-22 최댓값 : [ndarray 배열 객체].max(), np.max()
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.max(), np.max(a))
print(a.max(axis=0), np.max(a,axis=0))
print(a.max(axis=1), np.max(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9 9
[7 8 9] [7 8 9]
[3 6 9] [3 6 9]


## 4.2 브로드캐스팅 연산

shape가 다른 두 배열 사이의 이항 연산에서 브로드캐스팅 발생 </br>
두 배열을 같은 shape로 만든 후 연산을 수행


In [53]:
# 브로드캐스팅 사용하지 않은 경우
x = np.array([1,2,3,4,5])
y = np.array([1,1,1,1,1])
print(x+y)

# 브로드캐스팅을 사용한 경우
y=1
print(x+y)

[2 3 4 5 6]
[2 3 4 5 6]


In [54]:
# case 1 : 배열과 스칼라
# shape가 다른 두 배열의 연산
a = np.arange(1,25).reshape(4,6)
print(a+100) # 브로드캐스팅

# step 1 : 스칼라 배열 변경
new_arr = np.full_like(a,100)
print(new_arr)

# step 2 : 배열 이항 연산
print(a+new_arr)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
[[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [55]:
# case 2 : shape가 다른 배열들의 연산
a = np.arange(5).reshape((1,5))
print(a)
b = np.arange(5).reshape((5,1))
print(b)
print(a+b) # broadcasting

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


### 4.3 벡터 연산
배열 처리에 대한 벡터 연산을 적용할 경우 처리 속도가 100배 이상 향상된다.

### 5. 배열 변환
전치 : 행렬의 인덱스가 바뀌는 변환.

In [56]:
# 5.1 전치
a = np.random.randint(1,10,(3,3))
print(a)
print(a.T) # 전치 행렬

[[5 3 2]
 [3 7 4]
 [7 2 8]]
[[5 3 7]
 [3 7 2]
 [2 4 8]]


### 5.2 배열 형태 변경 

In [57]:
# 4-31 배열을 1차원 배열로 변환
a = np.array([[1,2,3],[4,5,6]])
print(a)
a.ravel()
b= a.ravel()
b[0]= 10
print(b)
print(a) # b 배열 변경이 a 행렬에 반영됨

[[1 2 3]
 [4 5 6]]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


[numpy.ndarray 객체].reshape() </br>


# 연습문제

In [60]:
# 연습 01
arr = np.arange(1,11)
print(arr)
print('ndim:',arr.ndim)
print(arr.shape)
print(arr.dtype)
print('size:',arr.size)

[ 1  2  3  4  5  6  7  8  9 10]
ndim: 1
(10,)
int64
size: 10


In [68]:
# 연습 02-1
arr = np.arange(10,51)
print(arr.ravel())

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [69]:
# 연습 02-2
arr = np.random.random((10,10))
print(arr.max())
print(arr.min())

0.9997372883611193
0.005974813979143789


In [71]:
# 연습 02-3
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
# 02-4
arr = np.arange(1,25).reshape(4,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [82]:
# 02-5
arr = np.arange(1,25).reshape(4,6)
print(arr[1:3,1:5])

[[ 8  9 10 11]
 [14 15 16 17]]


In [87]:
# 02-6
arr = np.arange(1,25).reshape(4,6)
print(arr[2::,::-1])

[[18 17 16 15 14 13]
 [24 23 22 21 20 19]]


In [88]:
# 02-7
print(arr[arr%2==0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [90]:
# 02-8
print(arr[(arr>=10) & (arr<21)]) # 소괄호를 쳐줘야함!

[10 11 12 13 14 15 16 17 18 19 20]


In [92]:
# 02-9 ??
import numpy as np
arr = np.arange(1,21)
print(arr[-1])
print(sum(arr))
print(sum(arr)/20)
# new_arr = 
print(new_arr)

20
210
10.5


In [95]:
# 02-10
import numpy as np
salary = [200,150,180,220,250]
new_salary = np.array(salary,dtype='float64')*1.5
print('인상된 금액', new_salary)
avg_salary = sum(new_salary)/5
print('평균 금액 : ', avg_salary)
result = new_salary[new_salary>=avg_salary]
print('평균 이상인 원소 : ', new_salary[result])
print('평균 이상인 원소의 개수 : ', size(new_salary))

인상된 금액 [300. 225. 270. 330. 375.]
평균 금액 :  300.0
[300. 330. 375.]


IndexError: arrays used as indices must be of integer (or boolean) type